### ISSUE TITLE
UnrepeatableReadError

### ISSUE THREAD

**Issue by AstraLuma** [AstraLuma/catfind#13]
```
2021-12-20T20:51:36.994145+00:00 app[scheduler.4565]: Updating OpenColorIO (https://opencolorio.readthedocs.io/en/latest/objects.inv)

2021-12-20T20:51:40.165852+00:00 app[scheduler.4565]: Traceback (most recent call last):

2021-12-20T20:51:40.165879+00:00 app[scheduler.4565]:   File "/app/.heroku/python/bin/flask", line 8, in <module>

2021-12-20T20:51:40.166012+00:00 app[scheduler.4565]:     sys.exit(main())

2021-12-20T20:51:40.166029+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/cli.py", line 994, in main

2021-12-20T20:51:40.166295+00:00 app[scheduler.4565]:     cli.main(args=sys.argv[1:])

2021-12-20T20:51:40.166302+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/cli.py", line 600, in main

2021-12-20T20:51:40.166486+00:00 app[scheduler.4565]:     return super().main(*args, **kwargs)

2021-12-20T20:51:40.166493+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1053, in main

2021-12-20T20:51:40.166765+00:00 app[scheduler.4565]:     rv = self.invoke(ctx)

2021-12-20T20:51:40.166775+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1659, in invoke

2021-12-20T20:51:40.167171+00:00 app[scheduler.4565]:     return _process_result(sub_ctx.command.invoke(sub_ctx))

2021-12-20T20:51:40.167180+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1395, in invoke

2021-12-20T20:51:40.167542+00:00 app[scheduler.4565]:     return ctx.invoke(self.callback, **ctx.params)

2021-12-20T20:51:40.167542+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke

2021-12-20T20:51:40.167775+00:00 app[scheduler.4565]:     return __callback(*args, **kwargs)

2021-12-20T20:51:40.167776+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func

2021-12-20T20:51:40.167843+00:00 app[scheduler.4565]:     return f(get_current_context(), *args, **kwargs)

2021-12-20T20:51:40.167859+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/cli.py", line 444, in decorator

2021-12-20T20:51:40.167994+00:00 app[scheduler.4565]:     return __ctx.invoke(f, *args, **kwargs)

2021-12-20T20:51:40.168002+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke

2021-12-20T20:51:40.168209+00:00 app[scheduler.4565]:     return __callback(*args, **kwargs)

2021-12-20T20:51:40.168217+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func

2021-12-20T20:51:40.168283+00:00 app[scheduler.4565]:     return f(get_current_context(), *args, **kwargs)

2021-12-20T20:51:40.168290+00:00 app[scheduler.4565]:   File "/app/catfind/__init__.py", line 270, in auto_index

2021-12-20T20:51:40.168398+00:00 app[scheduler.4565]:     ctx.invoke(index, url=proj.inv_url)

2021-12-20T20:51:40.168405+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke

2021-12-20T20:51:40.168628+00:00 app[scheduler.4565]:     return __callback(*args, **kwargs)

2021-12-20T20:51:40.168638+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func

2021-12-20T20:51:40.168711+00:00 app[scheduler.4565]:     return f(get_current_context(), *args, **kwargs)

2021-12-20T20:51:40.168718+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/cli.py", line 444, in decorator

2021-12-20T20:51:40.168876+00:00 app[scheduler.4565]:     return __ctx.invoke(f, *args, **kwargs)

2021-12-20T20:51:40.168883+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke

2021-12-20T20:51:40.169109+00:00 app[scheduler.4565]:     return __callback(*args, **kwargs)

2021-12-20T20:51:40.169117+00:00 app[scheduler.4565]:   File "<string>", line 2, in index

2021-12-20T20:51:40.169213+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/orm/core.py", line 552, in new_func

2021-12-20T20:51:40.169394+00:00 app[scheduler.4565]:     reraise(exc_type, exc, tb)

2021-12-20T20:51:40.169402+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/utils/utils.py", line 95, in reraise

2021-12-20T20:51:40.169482+00:00 app[scheduler.4565]:     try: raise exc.with_traceback(tb)

2021-12-20T20:51:40.169491+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/orm/core.py", line 533, in new_func

2021-12-20T20:51:40.169653+00:00 app[scheduler.4565]:     result = func(*args, **kwargs)

2021-12-20T20:51:40.169670+00:00 app[scheduler.4565]:   File "/app/catfind/__init__.py", line 203, in index

2021-12-20T20:51:40.169756+00:00 app[scheduler.4565]:     ent = Entry.get(project=proj, domain=domain, role=role, name=item.name)

2021-12-20T20:51:40.169772+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/orm/core.py", line 4014, in get

2021-12-20T20:51:40.170766+00:00 app[scheduler.4565]:     try: return entity._find_one_(kwargs)  # can throw MultipleObjectsFoundError

2021-12-20T20:51:40.170776+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/orm/core.py", line 4121, in _find_one_

2021-12-20T20:51:40.171856+00:00 app[scheduler.4565]:     if obj is None: obj = entity._find_in_db_(avdict, unique, for_update, nowait, skip_locked)

2021-12-20T20:51:40.171865+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/orm/core.py", line 4181, in _find_in_db_

2021-12-20T20:51:40.172913+00:00 app[scheduler.4565]:     objects = entity._fetch_objects(cursor, attr_offsets, 1, for_update, avdict)

2021-12-20T20:51:40.172922+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/orm/core.py", line 4315, in _fetch_objects

2021-12-20T20:51:40.174012+00:00 app[scheduler.4565]:     obj._db_set_(avdict)

2021-12-20T20:51:40.174021+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/orm/core.py", line 4951, in _db_set_

2021-12-20T20:51:40.175256+00:00 app[scheduler.4565]:     throw(UnrepeatableReadError,

2021-12-20T20:51:40.175281+00:00 app[scheduler.4565]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/utils/utils.py", line 106, in throw

2021-12-20T20:51:40.175373+00:00 app[scheduler.4565]:     raise exc

2021-12-20T20:51:40.175404+00:00 app[scheduler.4565]: pony.orm.core.UnrepeatableReadError: Value of Entry.last_indexed for OpenColorIO_v2_2dev::Baker::getFormatMetadata was updated outside of current transaction (was: datetime.datetime(2021, 12, 20, 20, 51, 36, 994208, tzinfo=datetime.timezone.utc), now: datetime.datetime(2021, 12, 20, 20, 51, 36, 994208))
```

**Comment by AstraLuma** [comment]
```
2021-12-20T22:23:28.101930+00:00 app[scheduler.1348]: Updating  (https://csgimu.readthedocs.io/en/latest/objects.inv)

2021-12-20T22:23:28.255102+00:00 app[scheduler.1348]: Traceback (most recent call last):

2021-12-20T22:23:28.255108+00:00 app[scheduler.1348]:   File "/app/.heroku/python/bin/flask", line 8, in <module>

2021-12-20T22:23:28.255263+00:00 app[scheduler.1348]:     sys.exit(main())

2021-12-20T22:23:28.255265+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/cli.py", line 994, in main

2021-12-20T22:23:28.255465+00:00 app[scheduler.1348]:     cli.main(args=sys.argv[1:])

2021-12-20T22:23:28.255475+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/cli.py", line 600, in main

2021-12-20T22:23:28.255625+00:00 app[scheduler.1348]:     return super().main(*args, **kwargs)

2021-12-20T22:23:28.255634+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1053, in main

2021-12-20T22:23:28.255906+00:00 app[scheduler.1348]:     rv = self.invoke(ctx)

2021-12-20T22:23:28.255915+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1659, in invoke

2021-12-20T22:23:28.256218+00:00 app[scheduler.1348]:     return _process_result(sub_ctx.command.invoke(sub_ctx))

2021-12-20T22:23:28.256226+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1395, in invoke

2021-12-20T22:23:28.256536+00:00 app[scheduler.1348]:     return ctx.invoke(self.callback, **ctx.params)

2021-12-20T22:23:28.256545+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke

2021-12-20T22:23:28.256714+00:00 app[scheduler.1348]:     return __callback(*args, **kwargs)

2021-12-20T22:23:28.256723+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func

2021-12-20T22:23:28.256796+00:00 app[scheduler.1348]:     return f(get_current_context(), *args, **kwargs)

2021-12-20T22:23:28.256797+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/cli.py", line 444, in decorator

2021-12-20T22:23:28.256908+00:00 app[scheduler.1348]:     return __ctx.invoke(f, *args, **kwargs)

2021-12-20T22:23:28.256916+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke

2021-12-20T22:23:28.257121+00:00 app[scheduler.1348]:     return __callback(*args, **kwargs)

2021-12-20T22:23:28.257132+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func

2021-12-20T22:23:28.257203+00:00 app[scheduler.1348]:     return f(get_current_context(), *args, **kwargs)

2021-12-20T22:23:28.257205+00:00 app[scheduler.1348]:   File "/app/catfind/__init__.py", line 270, in auto_index

2021-12-20T22:23:28.257289+00:00 app[scheduler.1348]:     ctx.invoke(index, url=proj.inv_url)

2021-12-20T22:23:28.257292+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke

2021-12-20T22:23:28.257456+00:00 app[scheduler.1348]:     return __callback(*args, **kwargs)

2021-12-20T22:23:28.257465+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func

2021-12-20T22:23:28.257564+00:00 app[scheduler.1348]:     return f(get_current_context(), *args, **kwargs)

2021-12-20T22:23:28.257572+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask/cli.py", line 444, in decorator

2021-12-20T22:23:28.257684+00:00 app[scheduler.1348]:     return __ctx.invoke(f, *args, **kwargs)

2021-12-20T22:23:28.257692+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke

2021-12-20T22:23:28.257900+00:00 app[scheduler.1348]:     return __callback(*args, **kwargs)

2021-12-20T22:23:28.257909+00:00 app[scheduler.1348]:   File "<string>", line 2, in index

2021-12-20T22:23:28.258003+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/orm/core.py", line 552, in new_func

2021-12-20T22:23:28.258157+00:00 app[scheduler.1348]:     reraise(exc_type, exc, tb)

2021-12-20T22:23:28.258166+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/utils/utils.py", line 95, in reraise

2021-12-20T22:23:28.258307+00:00 app[scheduler.1348]:     try: raise exc.with_traceback(tb)

2021-12-20T22:23:28.258314+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/orm/core.py", line 533, in new_func

2021-12-20T22:23:28.258491+00:00 app[scheduler.1348]:     result = func(*args, **kwargs)

2021-12-20T22:23:28.258494+00:00 app[scheduler.1348]:   File "/app/catfind/__init__.py", line 203, in index

2021-12-20T22:23:28.258577+00:00 app[scheduler.1348]:     ent = Entry.get(project=proj, domain=domain, role=role, name=item.name)

2021-12-20T22:23:28.258579+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/orm/core.py", line 4014, in get

2021-12-20T22:23:28.259292+00:00 app[scheduler.1348]:     try: return entity._find_one_(kwargs)  # can throw MultipleObjectsFoundError

2021-12-20T22:23:28.259294+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/orm/core.py", line 4121, in _find_one_

2021-12-20T22:23:28.260018+00:00 app[scheduler.1348]:     if obj is None: obj = entity._find_in_db_(avdict, unique, for_update, nowait, skip_locked)

2021-12-20T22:23:28.260028+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/orm/core.py", line 4181, in _find_in_db_

2021-12-20T22:23:28.260753+00:00 app[scheduler.1348]:     objects = entity._fetch_objects(cursor, attr_offsets, 1, for_update, avdict)

2021-12-20T22:23:28.260756+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/orm/core.py", line 4315, in _fetch_objects

2021-12-20T22:23:28.261515+00:00 app[scheduler.1348]:     obj._db_set_(avdict)

2021-12-20T22:23:28.261517+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/orm/core.py", line 4951, in _db_set_

2021-12-20T22:23:28.262561+00:00 app[scheduler.1348]:     throw(UnrepeatableReadError,

2021-12-20T22:23:28.262570+00:00 app[scheduler.1348]:   File "/app/.heroku/python/lib/python3.9/site-packages/pony/utils/utils.py", line 106, in throw

2021-12-20T22:23:28.262653+00:00 app[scheduler.1348]:     raise exc

2021-12-20T22:23:28.262688+00:00 app[scheduler.1348]: pony.orm.core.UnrepeatableReadError: Value of Entry.last_indexed for +csgimu was updated outside of current transaction (was: datetime.datetime(2021, 12, 20, 22, 23, 28, 101984, tzinfo=datetime.timezone.utc), now: datetime.datetime(2021, 12, 20, 22, 23, 28, 101984))
```

**Comment by AstraLuma** [comment]
Assuming these are intermittent problems, they should get resolved the next pass.

**Comment by AstraLuma** [comment]
I don't think this is actually concurrent changes. I wonder if it's duplicate entries in the inventory.

**Comment by AstraLuma** [comment]
* CAMP: `camp::CAMP_MAKE_L`
* Arbor: `arb::distributed_context::distributed_context`
* Solstice: Rules
* pySecDec: `name::complex_t`
* MHKiT: `mhkit.loads.general`
* ml4ai: `AnalysisGraph::AnalysisGraph`
* pybind11: `arg_v::arg_v`
* Musher: `musher::core::DecodeWav`

**Comment by AstraLuma** [comment]
4a7256344f92b2bb35f77a4c495aea5e4bd573a0 seems to have handled this.
