### ISSUE TITLE
Handle bad inventories

### ISSUE THREAD

**Issue by AstraLuma** [AstraLuma/catfind#15]
```
Updating  (https://bernardphp-com.readthedocs.io/projects/chute/objects.inv)
Traceback (most recent call last):
  File "/app/.heroku/python/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/app/.heroku/python/lib/python3.9/site-packages/flask/cli.py", line 994, in main
    cli.main(args=sys.argv[1:])
  File "/app/.heroku/python/lib/python3.9/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/flask/cli.py", line 444, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/catfind/__init__.py", line 270, in auto_index
    ctx.invoke(index, url=proj.inv_url)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/flask/cli.py", line 444, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "<string>", line 2, in index
  File "/app/.heroku/python/lib/python3.9/site-packages/pony/orm/core.py", line 533, in new_func
    result = func(*args, **kwargs)
  File "/app/catfind/__init__.py", line 184, in index
    inv = Inventory.load_uri(url)
  File "/app/catfind/inventory.py", line 121, in load_uri
    self = cls.load(
  File "/app/catfind/inventory.py", line 135, in load
    return cls.load_v2(reader, uri, joinfunc)
  File "/app/catfind/inventory.py", line 168, in load_v2
    raise ValueError('invalid inventory header (not compressed): %s' % line)
ValueError: invalid inventory header (not compressed): 
```

**Comment by AstraLuma** [comment]
```
Updating  (https://flint.readthedocs.io/projects/brick/en/latest/objects.inv)
Traceback (most recent call last):
  File "/app/.heroku/python/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/app/.heroku/python/lib/python3.9/site-packages/flask/cli.py", line 994, in main
    cli.main(args=sys.argv[1:])
  File "/app/.heroku/python/lib/python3.9/site-packages/flask/cli.py", line 600, in main
    return super().main(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/flask/cli.py", line 444, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/catfind/__init__.py", line 270, in auto_index
    ctx.invoke(index, url=proj.inv_url)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/flask/cli.py", line 444, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/app/.heroku/python/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "<string>", line 2, in index
  File "/app/.heroku/python/lib/python3.9/site-packages/pony/orm/core.py", line 533, in new_func
    result = func(*args, **kwargs)
  File "/app/catfind/__init__.py", line 184, in index
    inv = Inventory.load_uri(url)
  File "/app/catfind/inventory.py", line 121, in load_uri
    self = cls.load(
  File "/app/catfind/inventory.py", line 135, in load
    return cls.load_v2(reader, uri, joinfunc)
  File "/app/catfind/inventory.py", line 168, in load_v2
    raise ValueError('invalid inventory header (not compressed): %s' % line)
ValueError: invalid inventory header (not compressed): 
```

**Comment by AstraLuma** [comment]
* `https://array-split.readthedocs.io/en/latest/objects.inv`
* `https://django-simple-notifications.readthedocs.io/en/latest/objects.inv`
* `https://urecord.readthedocs.io/en/latest/objects.inv`
* `https://docs.lavasoftware.org/lavacli/objects.inv`
* `https://mailbot.readthedocs.io/en/latest/objects.inv`
* `https://galah-interact.readthedocs.io/en/latest/objects.inv`

**Comment by AstraLuma** [comment]
I bet a blank line in there is throwing it off.

**Comment by AstraLuma** [comment]
This one isn't a blank line: `https://pythonhosted.org/RecursiveDocument/objects.inv`

**Comment by AstraLuma** [comment]
The RecursiveDocument inventory has a newline in the middle instead of on the end.
